-- Create hospitals table
CREATE TABLE public.hospitals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  address TEXT,
  phone TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view hospitals" ON public.hospitals FOR SELECT USING (true);

-- Populate with some major hospitals (example data)
INSERT INTO public.hospitals (name, lat, lng, address) VALUES
('AIIMS DELHI', 28.5672, 77.2100, 'ANSARI NAGAR, NEW DELHI'),
('SAFDARJUNG HOSPITAL', 28.5668, 77.2081, 'SAFDARJUNG ENCLAVE, NEW DELHI'),
('RAM MANOHAR LOHIA HOSPITAL', 28.6250, 77.2025, 'BABA KHARAK SINGH MARG, NEW DELHI'),
('APOLLO HOSPITAL DELHI', 28.5284, 77.2842, 'SARITA VIHAR, DELHI'),
('MAX SUPER SPECIALITY HOSPITAL', 28.5276, 77.2117, 'SAKET, NEW DELHI'),
('FORTIS MEMORIAL RESEARCH INSTITUTE', 28.4595, 77.0726, 'GURUGRAM, HARYANA'),
('MEDANTA - THE MEDICITY', 28.4357, 77.0425, 'GURUGRAM, HARYANA'),
('SIR GANGA RAM HOSPITAL', 28.6385, 77.1895, 'RAJINDER NAGAR, NEW DELHI'),
('LADY HARDINGE MEDICAL COLLEGE', 28.6341, 77.2139, 'CONNAUGHT PLACE, NEW DELHI'),
('ST. STEPHEN''S HOSPITAL', 28.6655, 77.2205, 'TIS HAZARI, DELHI');
